site_name: IDOC Docs
site_url: https://idoc_docs.readthedocs.io/en/latest/
repo_url: https://github.com/shaliulab/idoc_docs
nav:
    - Home: index.md
    - Usage: usage.md
    - How to build:
        - Air delivery system: how-to-build/Air-odors-delivery-system.md
        - Electric Shock Circuit: how-to-build/Electric_Shock_Circuit.md
        - Enclosure breadboard system: how-to-build/Enclosure-Breadboard-System.md
        - Enclosure mounting: how-to-build/Enclosure-Camera-Mounting.md
        - Heatsink: how-to-build/Heatsink-Installation.md
        - IDOC Chamber assembly: how-to-build/IDOC-Chamber_Assembly.md
        - 3D parts: how-to-build/IDOC_3D_Assemply_Parts.md
        - IR Optogenetic System: how-to-build/IR-Optogenetic-System.md
        - List of commercial parts: how-to-build/List-of-Commercial-Parts-Tools.md
        - Wiring: how-to-build/Setup-Wiring-and-Powering-Cables.md

    - Installation:
        - Installation: installation.md
    - Analysis:
        - Analysis: analysis.md
    - Additional Info:
        - Fly food and crosses: fly-food-and-crosses.md
        - Sigmacote: sigmacote.md
        - FAQs: faqs.md

theme: readthedocs
