site_name: IDOC Docs
site_url: https://idoc_docs.readthedocs.io/en/latest/
repo_url: https://github.com/shaliulab/idoc_docs
nav:
    - Home: index.md
    - Usage: usage.md
    - How to build:
        - 3D parts: how-to-build/IDOC_3D_Assembly_Parts.md
        - Breadboard enclosure: how-to-build/Breadboard-Enclosure.md
        - Camera enclosure: how-to-build/Camera-Enclosure.md
        - Heatsink: how-to-build/Heatsink-Installation.md
        - IR Optogenetic System: how-to-build/IR-Optogenetic-System.md
        - Electric Shock Circuit: how-to-build/Electric_Shock_Circuit.md
        - Wiring: how-to-build/Setup-Wiring-and-Powering-Cables.md
        - Air delivery system: how-to-build/Air-odors-delivery-system.md
        - IDOC Chamber assembly: how-to-build/IDOC-Chamber_Assembly.md
        - Chamber holder: how-to-build/Chamber_holder.md
        - List of commercial parts: how-to-build/List-of-Commercial-Parts-Tools.md
        - Cleaning and maintenance: how-to-build/Cleaning_maintenance.md

    - Installation:
        - Installation: installation.md
    - Analysis:
        - Analysis: analysis.md
    - Additional Info:
        - FAQs: faqs.md

theme: readthedocs
